docker load < tiny-tools.tar                                                 
docker load < redis-master.tar                                               
docker load < prometheus:v1.7.0.tar                                          
docker load < node-exporter:v0.14.0.tar                                      
docker load < kube-state-metrics:v0.5.0.tar                                  
docker load < guestbook-redis-slave.tar                                      
docker load < guestbook-php-frontend.tar                                     
docker load < grafana:4.2.0.tar                                              
docker load < dockrload.sh                                                   
docker load < dockr.sh                                                       
docker load < caddy:0.9.3.tar                                                
docker load < alertmanager:v0.7.1.tar                                        
docker load < pause-amd64_3.0.tar                                            
docker load < kubernetes-dashboard-amd64_1.6.3.tar                           
docker load < kube-scheduler-amd64_v1.7.2.tar                                
docker load < kube-proxy-amd64_v1.7.2.tar                                    
docker load < kube-controller-manager-amd64_v1.7.2.tar                       
docker load < kube-apiserver-amd64_v1.7.2.tar                                
docker load < k8s-dns-sidecar-amd64_1.14.4.tar                               
docker load < k8s-dns-kube-dns-amd64_1.14.4.tar                              
docker load < k8s-dns-dnsmasq-nanny-amd64_1.14.4.tar                         
docker load < flannel-amd64_v0.8.0.tar                                       
docker load < etcd_v3.0.17.tar                                               

